# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Arma_colSums <- function(x) {
    .Call('_ADMMRcppArma_Arma_colSums', PACKAGE = 'ADMMRcppArma', x)
}

cumsum_rev <- function(m) {
    .Call('_ADMMRcppArma_cumsum_rev', PACKAGE = 'ADMMRcppArma', m)
}

cumsum_col <- function(m) {
    .Call('_ADMMRcppArma_cumsum_col', PACKAGE = 'ADMMRcppArma', m)
}

